### PR TITLE
Update favicon

### PR DESCRIPTION
**Pull request by parammittal16**
Issue https://github.com/ZetaGlest/zetaglest.github.io/issues/75

### CODE REVIEW

**Review by andy5995 — COMMENTED** [review]
image

Thank you. That's a nice icon. What is it's source and License?

**Comment by parammittal16** [comment]
Hi @andy5995,
https://www.flaticon.com/free-icon/antivirus_1086622#term=sword&page=1&position=64 this is the source.
For the free licence, you can refer to it while downloading it.
I download this as a png and converted it as ico online.

Hope this helps !

**Comment by andy5995** [comment]
The license requirements on that page state:

>For websites:
Insert the attribution on the page of the icon (for example in the page footer) or on the imprint page.

We'd like to avoid that. Adding that info to a footer for each item would get rather cluttered.

Artwork and icons that allow credit to be just mentioned in documentation is preferable. Or public domain would be ok. Most of the stuff we use is licensed as CC Creative Attribution-ShareAlike 3.0 Unported

Also original artwork with a declared license by our team and contributors is welcome too. That's a case where we'd document it in a file, such as https://github.com/ZetaGlest/zetaglest-data/blob/develop/docs/AUTHORS.data.txt

**Comment by parammittal16** [comment]
https://www.kisspng.com/png-computer-icons-shield-sword-weapon-clip-art-1565046/download-png.html

Refered this from here

**Comment by andy5995** [comment]
Though it's nice, we won't use this because of the  license requirement.

**Pull request closed without merging**
